/* 사용자가 실제로 붙여넣을 법한 코드 모음.
 *
 * samples.js / dev/cases.js 는 **내가 고른** 코드다. 잘 나오게 생긴 것만
 * 모여 있을 수밖에 없다. 여기는 그 바깥을 재려고 만든 것이다 —
 * 학원·인강·블로그 풀이에서 흔한 꼴, 특히
 *   - 전부 함수 안에 넣고 main() 을 부르는 꼴
 *   - 클래스로 감싼 자료구조
 *   - 딕셔너리의 딕셔너리
 *   - 헬퍼 함수를 여러 개 두는 꼴
 * 을 일부러 넣었다. 이런 코드에서 그림이 죽으면 도구가 쓸모없다.
 *
 * 이 파일은 화면에 안 나온다. 재는 용도다. */
window.USERLIKE = {

main_wrap: [
  "def solve(arr):",
  "    n = len(arr)",
  "    for i in range(n):",
  "        for j in range(0, n - i - 1):",
  "            if arr[j] > arr[j + 1]:",
  "                arr[j], arr[j + 1] = arr[j + 1], arr[j]",
  "    return arr",
  "",
  "def main():",
  "    data = [5, 3, 8, 1, 9, 2, 7]",
  "    out = solve(data)",
  "    print(out)",
  "",
  "main()",
].join("\n"),

class_uf: [
  "class UnionFind:",
  "    def __init__(self, n):",
  "        self.parent = list(range(n))",
  "        self.size = [1] * n",
  "",
  "    def find(self, x):",
  "        while self.parent[x] != x:",
  "            x = self.parent[x]",
  "        return x",
  "",
  "    def union(self, a, b):",
  "        ra, rb = self.find(a), self.find(b)",
  "        if ra == rb:",
  "            return False",
  "        self.parent[rb] = ra",
  "        self.size[ra] += self.size[rb]",
  "        return True",
  "",
  "uf = UnionFind(6)",
  "edges = [(0, 1), (1, 2), (3, 4), (2, 3), (0, 5)]",
  "joined = 0",
  "for a, b in edges:",
  "    if uf.union(a, b):",
  "        joined += 1",
  "print(joined, uf.parent)",
].join("\n"),

dict_of_dict: [
  "graph = {",
  "    'A': {'B': 3, 'C': 1},",
  "    'B': {'A': 3, 'D': 2},",
  "    'C': {'A': 1, 'D': 5},",
  "    'D': {'B': 2, 'C': 5},",
  "}",
  "dist = {k: 99 for k in graph}",
  "dist['A'] = 0",
  "done = set()",
  "for _ in range(len(graph)):",
  "    cur = None",
  "    for k in graph:",
  "        if k not in done and (cur is None or dist[k] < dist[cur]):",
  "            cur = k",
  "    done.add(cur)",
  "    for nx, w in graph[cur].items():",
  "        if dist[cur] + w < dist[nx]:",
  "            dist[nx] = dist[cur] + w",
  "print(dist)",
].join("\n"),

triple_heap: [
  "import heapq",
  "adj = {0: [(1, 4), (2, 1)], 1: [(3, 1)], 2: [(1, 2), (3, 5)], 3: []}",
  "pq = [(0, 0)]",
  "dist = {0: 0, 1: 99, 2: 99, 3: 99}",
  "while pq:",
  "    cost, node = heapq.heappop(pq)",
  "    if cost > dist[node]:",
  "        continue",
  "    for nx, w in adj[node]:",
  "        if cost + w < dist[nx]:",
  "            dist[nx] = cost + w",
  "            heapq.heappush(pq, (cost + w, nx))",
  "print(dist)",
].join("\n"),

sort_multikey: [
  "people = [('kim', 3, 90), ('lee', 1, 90), ('park', 2, 75), ('choi', 4, 88)]",
  "ranked = sorted(people, key=lambda p: (-p[2], p[1]))",
  "names = []",
  "for name, num, score in ranked:",
  "    names.append(name)",
  "print(ranked)",
  "print(names)",
].join("\n"),

enum_zip: [
  "names = ['a', 'b', 'c', 'd']",
  "scores = [70, 95, 82, 60]",
  "pairs = []",
  "for i, (nm, sc) in enumerate(zip(names, scores)):",
  "    pairs.append((i, sc))",
  "total = 0",
  "for i, sc in pairs:",
  "    total += sc",
  "print(pairs, total / len(pairs))",
].join("\n"),

build_string: [
  "words = ['algo', 'viz', 'step', 'wise']",
  "parts = []",
  "for w in words:",
  "    parts.append(w.upper())",
  "joined = '-'.join(parts)",
  "counts = {}",
  "for ch in joined:",
  "    counts[ch] = counts.get(ch, 0) + 1",
  "print(joined, counts)",
].join("\n"),

window_dict: [
  's = "abcabcbb"',
  "seen = {}",
  "left = 0",
  "best = 0",
  "for right, ch in enumerate(s):",
  "    if ch in seen and seen[ch] >= left:",
  "        left = seen[ch] + 1",
  "    seen[ch] = right",
  "    if right - left + 1 > best:",
  "        best = right - left + 1",
  "print(best)",
].join("\n"),

backtrack_str: [
  "def build(cur, depth, out):",
  "    if depth == 3:",
  "        out.append(cur)",
  "        return",
  '    for c in "ab":',
  "        build(cur + c, depth + 1, out)",
  "",
  "res = []",
  'build("", 0, res)',
  "print(res)",
].join("\n"),

list_pop0: [
  "queue = [1]",
  "visited = [False] * 7",
  "graph = [[1, 2], [0, 3], [0, 4], [1], [2, 5], [4, 6], [5]]",
  "order = []",
  "visited[1] = True",
  "while queue:",
  "    cur = queue.pop(0)",
  "    order.append(cur)",
  "    for nx in graph[cur]:",
  "        if not visited[nx]:",
  "            visited[nx] = True",
  "            queue.append(nx)",
  "print(order)",
].join("\n"),

digits_loop: [
  "n = 91827",
  "digits = []",
  "total = 0",
  "while n > 0:",
  "    d = n % 10",
  "    digits.append(d)",
  "    total += d",
  "    n //= 10",
  "digits.reverse()",
  "print(digits, total)",
].join("\n"),

state_machine: [
  "tokens = ['push 3', 'push 5', 'add', 'push 2', 'mul', 'end']",
  "stack = []",
  "log = []",
  "for t in tokens:",
  "    if t == 'end':",
  "        break",
  "    if t.startswith('push'):",
  "        stack.append(int(t.split()[1]))",
  "        log.append('push')",
  "    elif t == 'add':",
  "        b = stack.pop()",
  "        a = stack.pop()",
  "        stack.append(a + b)",
  "        log.append('add')",
  "    elif t == 'mul':",
  "        b = stack.pop()",
  "        a = stack.pop()",
  "        stack.append(a * b)",
  "        log.append('mul')",
  "print(stack, log)",
].join("\n"),

helper_chain: [
  "def read_data():",
  "    return [4, 8, 15, 16, 23, 42]",
  "",
  "def normalize(xs):",
  "    lo = min(xs)",
  "    hi = max(xs)",
  "    out = []",
  "    for x in xs:",
  "        out.append(round((x - lo) / (hi - lo), 2))",
  "    return out",
  "",
  "def bucketize(xs, k):",
  "    out = [[] for _ in range(k)]",
  "    for x in xs:",
  "        out[min(k - 1, int(x * k))].append(x)",
  "    return out",
  "",
  "raw = read_data()",
  "norm = normalize(raw)",
  "buckets = bucketize(norm, 4)",
  "print(norm)",
  "print(buckets)",
].join("\n"),

grid_comprehension: [
  "n = 5",
  "board = [[0] * n for _ in range(n)]",
  "for i in range(n):",
  "    for j in range(n):",
  "        if (i + j) % 3 == 0:",
  "            board[i][j] = 1",
  "rows = []",
  "for r in board:",
  "    rows.append(sum(r))",
  "print(rows)",
].join("\n"),

try_except: [
  "vals = ['3', '7', 'x', '12', '', '5']",
  "nums = []",
  "bad = []",
  "for v in vals:",
  "    try:",
  "        nums.append(int(v))",
  "    except ValueError:",
  "        bad.append(v)",
  "avg = sum(nums) / len(nums)",
  "print(nums, bad, avg)",
].join("\n"),

top_n_dict: [
  'text = "the quick brown fox jumps over the lazy dog the fox"',
  "freq = {}",
  "for w in text.split():",
  "    freq[w] = freq.get(w, 0) + 1",
  "ranked = sorted(freq.items(), key=lambda kv: (-kv[1], kv[0]))",
  "top3 = ranked[:3]",
  "print(freq)",
  "print(top3)",
].join("\n"),

matrix_class: [
  "class Matrix:",
  "    def __init__(self, rows):",
  "        self.rows = rows",
  "        self.n = len(rows)",
  "",
  "    def transpose(self):",
  "        out = []",
  "        for i in range(self.n):",
  "            row = []",
  "            for j in range(self.n):",
  "                row.append(self.rows[j][i])",
  "            out.append(row)",
  "        return Matrix(out)",
  "",
  "    def trace(self):",
  "        t = 0",
  "        for i in range(self.n):",
  "            t += self.rows[i][i]",
  "        return t",
  "",
  "m = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])",
  "t = m.transpose()",
  "print(m.rows)",
  "print(t.rows)",
  "print(m.trace())",
].join("\n"),

nested_func: [
  "def outer(data):",
  "    seen = set()",
  "",
  "    def visit(x):",
  "        if x in seen:",
  "            return 0",
  "        seen.add(x)",
  "        total = x",
  "        for nx in data.get(x, []):",
  "            total += visit(nx)",
  "        return total",
  "",
  "    return visit(1)",
  "",
  "tree = {1: [2, 3], 2: [4], 3: [5, 6], 4: [], 5: [], 6: []}",
  "print(outer(tree))",
].join("\n"),

two_arrays_merge: [
  "a = [1, 4, 7, 9]",
  "b = [2, 3, 8, 10, 11]",
  "i = 0",
  "j = 0",
  "merged = []",
  "while i < len(a) and j < len(b):",
  "    if a[i] <= b[j]:",
  "        merged.append(a[i])",
  "        i += 1",
  "    else:",
  "        merged.append(b[j])",
  "        j += 1",
  "while i < len(a):",
  "    merged.append(a[i])",
  "    i += 1",
  "while j < len(b):",
  "    merged.append(b[j])",
  "    j += 1",
  "print(merged)",
].join("\n"),

set_ops: [
  "A = set([1, 2, 3, 4, 5])",
  "B = set([4, 5, 6, 7])",
  "inter = A & B",
  "uni = A | B",
  "diff = A - B",
  "grown = set()",
  "for x in sorted(uni):",
  "    grown.add(x * 2)",
  "print(inter, uni, diff, grown)",
].join("\n"),

memo_dict_tuple: [
  "memo = {}",
  "",
  "def ways(r, c):",
  "    if r == 0 or c == 0:",
  "        return 1",
  "    if (r, c) in memo:",
  "        return memo[(r, c)]",
  "    memo[(r, c)] = ways(r - 1, c) + ways(r, c - 1)",
  "    return memo[(r, c)]",
  "",
  "print(ways(3, 3))",
  "print(len(memo))",
].join("\n"),

deque_rotate: [
  "from collections import deque",
  "dq = deque([1, 2, 3, 4, 5, 6])",
  "picked = []",
  "k = 3",
  "while dq:",
  "    dq.rotate(-(k - 1))",
  "    picked.append(dq.popleft())",
  "print(picked)",
].join("\n"),

float_series: [
  "vals = [1.5, 2.25, 3.125, 4.0625]",
  "acc = []",
  "run = 0.0",
  "for v in vals:",
  "    run += v",
  "    acc.append(round(run, 3))",
  "mean = run / len(vals)",
  "print(acc, round(mean, 3))",
].join("\n"),

sort_string_list: [
  'words = ["banana", "apple", "cherry", "date", "fig"]',
  "words.sort()",
  'target = "cherry"',
  "lo = 0",
  "hi = len(words) - 1",
  "found = -1",
  "while lo <= hi:",
  "    mid = (lo + hi) // 2",
  "    if words[mid] == target:",
  "        found = mid",
  "        break",
  "    if words[mid] < target:",
  "        lo = mid + 1",
  "    else:",
  "        hi = mid - 1",
  "print(words, found)",
].join("\n"),

};
"userlike " + Object.keys(window.USERLIKE).length;
